name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      # Todo: remove the test exclusion part for the core repo after the tests get fixed
      - name: Building dagger core. All dependent sub project would be built as part of this
        run: ./gradlew build
