name: integration-test

on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  integration-test:
    runs-on: ubuntu-latest
    env:
      flinkVersion: "1.9.0"
      POSTGRES_DB: test_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_HOST_AUTH_METHOD: trust
    services:
      postgres:
        image: postgres:12.2-alpine
      elasticsearch:
        env:
          xpack.security.enabled: false
          discovery.type: single-node
        image: elasticsearch:6.8.3
        ports:
          - 9200/tcp
        options: -e="discovery.type=single-node" --health-cmd="curl http://localhost:9200/_cluster/health" --health-interval=10s --health-timeout=5s --health-retries=10
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Verify external connections from host
        env:
          ELASTIC_SEARCH_URL: http://localhost:${{ job.services.elasticsearch.ports[9200] }}
        run: |
          echo $ELASTIC_SEARCH_URL
          curl -fsSL "$ELASTIC_SEARCH_URL/_cat/health?h=status"
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Run test
        run: PG_HOST=postgres ES_HOST=localhost ./gradlew integrationTest
