name: Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Building dagger core. All dependent sub project would be built as part of this
        run: ./gradlew build

  publishJar:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Publish packages of common subprojects
        run: ./gradlew :dagger-common:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish packages of core
        run: ./gradlew :dagger-core:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
