name: py-package
on:
  push:
    branches:
      - dagger-py-functions
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Zip dagger-py-functions
        run: zip -r dagger-py-functions.zip $GITHUB_WORKSPACE/dagger-py-functions
      - name: Show Files
        run: ls -a
      - name: Publish Package
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Show Files again
        run: ls -a